### ISSUE TITLE
How to load balance different grid areas separately, to create multiple partitions per process

### ISSUE THREAD

**Issue by galfthan** [fmihpc/dccrg#5]
When doing subcycling in Gumics 5 there is significant LB issues as the processes owning the cells with the smallest dt will be the bottleneck. 

One possibility for improving LB would be to partition each subcycling level separately. Then each process would have one partition per subcycling level. This should lead to better balance, at the cost of greater communication overhead as the number of remote cellls would increase.

Can this be accomplished with the current version of DCCRG? If not, then this can be relabeled as a feature request.

**Comment by iljah** [comment]
> When doing subcycling in Gumics 5 there is significant LB issues as the
> processes owning the cells with the smallest dt will be the bottleneck.
> One possibility for improving LB would be to partition each subcycling
> level separately. Then each process would have one partition per
> subcycling level. This should lead to better balance, at the cost of
> greater communication overhead as the number of remote cellls would
> increase.

I'm not sure I understand, do you mean more than one process would own 
the same cell? How would that be better than making sure that smallest 
dt cells are distributed more evenly between processes? No matter how 
the work is distributed some processes will have to wait while other 
processes with smaller dt cells are calculating the solution.

I'd try a custom load balancer first, one which e.g. distributes cells 
in slices around Z axis so that all processes get cells of all dt sizes.

> Can this be accomplished with the current version of DCCRG? If not, then
> this can be relabeled as a feature request.

Most likely not and seems like it would be a very big change to make happen.

**Comment by galfthan** [comment]
No, one cell would be owned by one process. The point is exactly to distribute the small dt cells more evenly. 

Let's say there are two levels, dt and 2dt and N processes. The point would be to first partition all cells with dt timestep to all N processes. Then all cells with timestep of 2dt would be partitioned to the same Nprocesses. Each process would then typically have two separate regions, one with cells with timestep = dt and one wiht cells with timestep = 2dt

**Comment by galfthan** [comment]
I guess it should not be that difficult. One would need to just ask Zoltan multiple time to partition the different sets of cells.

**Comment by iljah** [comment]
> I guess it should not be that difficult. One would need to just ask
> Zoltan multiple time to partition the different sets of cells.

A quick hack would be to pin all cells that aren't to be partitioned to 
their current process and run zoltan, unpin the next time step level and 
repeat.

**Comment by galfthan** [comment]
Will that work correctly? Will not DCCRG and zoltan take into account the weight of the already pinned cells when computing the partition for the unpinned ones? 

Even if it does, I guess one could perhaps work around that by setting the weight of the pinned one to zero...

**Comment by iljah** [comment]
> Will that work correctly? Will not DCCRG and zoltan take into account
> the weight of the already pinned cells when computing the partition for
> the unpinned ones?
> Even if it does, I guess one could perhaps work around that by setting
> the weight of the pinned one to zero...

Zoltan will try to balance everything and dccrg won't transfer pinned 
cells. Not sure if that's a good or a bad thing. I guess zoltan could be 
informed only about unpinned cells but that might not improve things.

**Comment by galfthan** [comment]
Then it will not work. One should tell Zoltan only about unpinned cells, then one could partition the unpinned cells among all processes. Why would it not work in that case?

**Comment by iljah** [comment]
> Then it will not work. One should tell Zoltan only about unpinned cells,
> then one could partition the unpinned cells among all processes. Why
> would it not work in that case?

I'm guessing partition quality would be bad as zoltan could send nearby 
cells with different dts to different processes so you could end up with 
one process owing cells of different dt that are not close to each 
other. Whereas if zoltan is told about all cells it can at least 
consider not moving one layer of cells to another process if they're 
already close to another layer of cells on the same process. But one 
would probably need several iterations of load balancing since not all 
cells would move as zoltan wanted.

**Comment by ykempf** [comment]
Chiming in here... Wouldn't giving a factor of 2 (or more) higher weight to dt cells wrt 2dt cells do a good part of the trick?

**Comment by galfthan** [comment]
Not really. The point is that each level should be paralellized. If ach process only has one domain then each timestep region is parallelized to a much smaller number of processes. Since these are synchronized, this hinders performance.  Thi is visible in G5, the latest version is spending basically all its time on load imbalance.

**Comment by iljah** [comment]
I created a specific issue for skipping cells with Zoltan so closing this one: https://github.com/fmihpc/dccrg/issues/15
If I misunderstood the feature request please reopen this one or create one or more new ones...
